### PR TITLE
re-add revengStrategy parameter

### PR DESCRIPTION
**Pull request by dgf**
Or is there another way to generically customize the class names?

### CODE REVIEW

**Comment by stadler** [comment]
Looks great to me.
The only thing that I think that could be improved is to add some javadoc to the new parameter, even though the other ones currently don't have any.
Because #842 will add proper javadoc to all the other parameters and ensures that a site is generated.

**Comment by dgf** [comment]
Is there anything else I can do to get this adaptation into a 5.3.* release?

**Comment by stadler** [comment]
To me it looks fine. 
But I think it is up to @koentsje to further review/merge it.

**Comment by koentsje** [comment]
Hey guys I can merge it for now but for HT 6, I am reshuffling the classes so it's possible the classname (or at least the package) will change. Thanks for the contribution in any case!

**Comment by koentsje** [comment]
I rebased the branch and cherry-picked the commits in the 5.3/5.4/6.0 branches.
Thanks again!

**Pull request closed without merging**
