### PR TITLE
HBX-1226 Generated equals(Object) implementation doesn't support lazy proxies

### PR DESCRIPTION
**Pull request by karlvr**
Replaces #45.

The fault is in the equals(Object other) implementation when other is a proxy, because the method uses instanceof to check if other is an instanceof the class. My solution uses Hibernate.getClass(Object), which is proxy aware, and compares that with == to getClass(). This is semantically different, obviously, as previously we had instanceof. We could replicate the old behaviour with getClass().isAssignableFrom(Hibernate.getClass(other)), but I think that comparing that we are the identical class is more correct.

This does also require that the proxy interface implements all of the methods that we include in the equals computation. I don't think this is a bad requirement, but it is an extra requirement. We could bypass this requirement by busting open the proxy, but I think that's a little dirty.

I think this is a really important change as it introduces some very weird and subtle behaviour that results in unexpected failures. Specifically, note the testTwoIdenticalProxiesAreNotEqual() method where we demonstrate that for two proxies of the same object: p1 == p2 && !p1.equals(p2), which is pretty darn weird!

### CODE REVIEW

**Comment by koentsje** [comment]
In an effort to integrate this and verify the problem, I had cherry-picked commits 78fe14c, 940f192 and 0b53234 into the 5.1 branch. But the resulting test run is successful so I am not sure if the test properly demonstrates the problem of if maybe I missed something?

**Comment by karlvr** [comment]
@koentsje I've added (and corrected) the documentation in the two beans associated with the test cases to explain how they are used to demonstrate the problem and the fix. I hope this makes sense now.

**Comment by koentsje** [comment]
@karlvr Ok, I grok the changes now and it looks good. Only I think that, instead of using fixed pre-created beans, the tests that demonstrate the problem should use the hbm2java generation to generate some code that eventually results in a test that  *fails* as long as the changes from commit 2ae527c are not applied. Let me look at how we can deal with this.

**Comment by koentsje** [comment]
@karlvr I also am wondering why you think that it is more correct to have identical classes in the 'equals' implementation than using 'isAssignableFrom()' to check for instances of the class/interface? I'm not sure if it will ever happen but if you define the semantics of 'equals' to be that the ids of both entities should be the same, then the actual class should probably not be identical.

**Comment by karlvr** [comment]
@koentsje I wasn't sure about getting hbm2java to revert to the old behaviour, without adding code to make it an option when it probably shouldn't be. Perhaps we could use hbm2java to generate the new beans and verify that _they_ work as expected?

**Comment by karlvr** [comment]
@koentsje I thought for a while about the equals implementation and I'm not 100% sure either way. I was swayed by the default implementation that Eclipse generates, which checks that the classes are the same.

If the classes _aren't_ the same then it's not equal. I think that's fair actually. In a Hibernate situation I don't _think_ there's a case where an object would be considered equal and not be the exact same class. But it would be possible to setup two separate entities in the database, with separate id spaces, and have the implementation class of one extend the other, in which case `isAssignableFrom()` would be true, and the ids could match as they're separate entity tables, and we'd get a false positive.

So I guess now I am pretty sure that it needs to be equal classes!

**Comment by koentsje** [comment]
@karlvr I see two problems with this approach. The first and obvious one is that you add a dependency on the Hibernate runtime for the generated entities, which is something we want to avoid. The second problem is that I think that in the context of ORM the equality does not at all require that the classes are the same. Equality in the context of the entities implies that they represent the same row in the database. Two objects that are instances of different classes in the same class hierarchy can very well indicate the same row in a database and hence should be able to be equal. These two reasons is why I prefer to keep the 'instanceof' check. I have tried to solve the problem as I understood it and opened #57. Would you be able to take a look at this PR and see if it solves the problem you are experiencing? The first commit of this PR adds two tests that show the problem, the second commit is the fix.

**Comment by karlvr** [comment]
@koentsje I can't currently see a situation where the ORM provides two objects that represent the same row in the database that don't have the same class (after resolving proxies). Could you elaborate on that case?

**Comment by koentsje** [comment]
@karlvr I have integrated #57 in the 5.0, 5.1 and master branches. As for the class equality issue, please take a look at 2279170. Let's continue the discussion there if needed.

**Pull request closed without merging**
