### PR TITLE
HBX-2041: Add GenerateDaoMojo (hbm2dao) to generate DAOs with the mav…

### PR DESCRIPTION
**Pull request by eciuca**
…en plugin

### CODE REVIEW

**Comment by eciuca** [comment]
@koentsje I think this one is ready for merging (I added the test but I couldn't mark the change as implemented)

**Comment by eciuca** [comment]
I saw you merged this one: https://github.com/hibernate/hibernate-tools/pull/2023

**Comment by koentsje** [comment]
i am still in the process of back porting it to the older branches

**Comment by mmm8955405** [comment]
Add support for setting class file names and paths, such as hbmtemplate filepattern

**Pull request closed without merging**
